services:
  linkedin_publisher:
    build: .
    container_name: linkedin_publisher
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
    env_file: .env
    volumes:
      - ./chrome_profile:/app/chrome_profile
      - ./data:/app/data
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
